# Jekyll config file

title: Guid'me Tech
logo: /assets/logo.png

email_contact: contact@guidme.fr
author:
  name: Guid'me
  email: jeremy.pichon@guidme.fr

description: >-
  Guid’me is French company that helps travelers to enjoy the best of any country with local guides.
  This website will contains all Open Source projects and blog posts from our Engineers.

url: "https://guidme.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

# Theme
theme: minima

# Minima theme configuration
minima:
  # classic, dark, solarized, solarized-dark
  skin: classic
  date_format: "%b %-d, %Y"
  social_links:
    github: guidme
    facebook: appguidme
    instagram: appguidme
    linkedin: guidme
    twitter: false

# Reorder the navigation menus
header_pages:
  - blog.md
  - open-source.md
  - team.md
  - about.md

collections:
  authors:
    title: Authors
    output: true

# Plugins to enable
plugins:
  - jekyll-feed

# Change to true to show post preview in list
# See: https://jekyllrb.com/docs/posts/#post-excerpts
show_excerpts: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
